name: ringdoorbell
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - sqlalchemy
  - alembic
  - pydantic
  - pytest
  - pytest-asyncio
  - httpx
  - sqlite
  - pip
  - pip:
    - ring-doorbell
