

"""remove_video_data_column

Revision ID: 88ede934de01
Revises: cdbf69282f00
Create Date: 2025-05-03 20:59:16.027438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ede934de01'
down_revision = 'cdbf69282f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_column('ring_events', 'video_data')
    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('ring_events', sa.Column('video_data', sa.BLOB(), nullable=True))
    