

"""add_video_fields_to_ring_events

Revision ID: cdbf69282f00
Revises: d3d71f9d4d96
Create Date: 2025-05-03 18:23:36.264917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdbf69282f00'
down_revision = 'd3d71f9d4d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ring_events', sa.Column('has_video', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('ring_events', sa.Column('video_data', sa.LargeBinary(), nullable=True))
    op.add_column('ring_events', sa.Column('recording_id', sa.Integer(), nullable=True))
    op.add_column('ring_events', sa.Column('video_url', sa.String(length=500), nullable=True))
    
    # Create an index on has_video for faster querying
    op.create_index(op.f('ix_ring_events_has_video'), 'ring_events', ['has_video'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ring_events_has_video'), table_name='ring_events')
    op.drop_column('ring_events', 'video_url')
    op.drop_column('ring_events', 'recording_id')
    op.drop_column('ring_events', 'video_data')
    op.drop_column('ring_events', 'has_video')
    # ### end Alembic commands ###