

"""remove_obsolete_tables

Revision ID: d3d71f9d4d96
Revises: f14d4b891b2e
Create Date: 2025-05-02 12:51:15.996254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3d71f9d4d96'
down_revision = 'f14d4b891b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before dropping them
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    
    if 'capture_metadata' in inspector.get_table_names():
        op.drop_table('capture_metadata')
    
    if 'ring_captures' in inspector.get_table_names():
        op.drop_table('ring_captures')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate ring_captures table
    op.create_table('ring_captures',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('capture_type', sa.String(length=50), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('event_metadata', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ring_captures_id'), 'ring_captures', ['id'], unique=False)
    
    # Recreate capture_metadata table
    op.create_table('capture_metadata',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('image_path', sa.String(), nullable=False),
        sa.Column('video_path', sa.String(), nullable=True),
        sa.Column('timestamp', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_metadata_id'), 'capture_metadata', ['id'], unique=False)
    # ### end Alembic commands ###