

"""Create ring_events table

Revision ID: f14d4b891b2e
Revises: 
Create Date: 2025-05-02 12:04:42.429505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14d4b891b2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capture_metadata_id'), 'capture_metadata', ['id'], unique=False)
    op.create_table('ring_captures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capture_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('event_metadata', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ring_captures_id'), 'ring_captures', ['id'], unique=False)
    op.create_table('ring_events',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('event_data', sa.Text(), nullable=False),
    sa.Column('stored_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ring_events_created_at'), 'ring_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_ring_events_device_id'), 'ring_events', ['device_id'], unique=False)
    op.create_index(op.f('ix_ring_events_id'), 'ring_events', ['id'], unique=False)
    op.create_index(op.f('ix_ring_events_kind'), 'ring_events', ['kind'], unique=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ring_events_kind'), table_name='ring_events')
    op.drop_index(op.f('ix_ring_events_id'), table_name='ring_events')
    op.drop_index(op.f('ix_ring_events_device_id'), table_name='ring_events')
    op.drop_index(op.f('ix_ring_events_created_at'), table_name='ring_events')
    op.drop_table('ring_events')
    op.drop_index(op.f('ix_ring_captures_id'), table_name='ring_captures')
    op.drop_table('ring_captures')
    op.drop_index(op.f('ix_capture_metadata_id'), table_name='capture_metadata')
    op.drop_table('capture_metadata')
    # ### end Alembic commands ###
    # ### end Alembic commands ###